dist: trusty

language: python

python: 3.6

cache:
    pip: true
    apt: true
    directories:
    - ./smt_solvers

env:
    - SOLVER=Z3
    - SOLVER=CVC4
    - SOLVER=Boolector

addons:
    apt:
        sources:
           - ubuntu-toolchain-r-test
        packages:
            #            - libpython3-all-dev
            - libgmp3-dev
            - git
            - cmake
            - zlib1g
            - zlib1g-dev
            - git
            - g++-4.9
            - build-essential
            - swig2.0
            - libcln-dev

before_install:
    - export CXX="g++-4.9"
    - export CC="gcc-4.9"
    - export COREIRCONFIG="g++-4.9"

install:
    - . ./util/get_smt_solvers.sh
    # Add smt-switch
    - git clone https://github.com/makaimann/smt-switch.git
    - export PYTHONPATH=$PYTHONPATH:$PWD/smt-switch
    - cd $TRAVIS_BUILD_DIR
    # Build coreir
    - git clone -b dev -- https://github.com/rdaly525/coreir.git
    - cd coreir;
    - make -j2 all
    - sudo make -j2 install
    - pip install coreir
    - pip install pytest
    - pip install --upgrade coreir
    - pip install --upgrade pytest
    #- make -C src
    #- make -C src ../build/coreir.so  # For bindings tests
    #- make -C tests
    - cd $TRAVIS_BUILD_DIR
    - pip install -e package

script:
    - echo Running tests with $SOLVER
    - ./test/test.sh
