language: python3

addons:
    apt:
        packages:
            - libgmp3-dev
            - git
            - cmake
            - zlib1g
            - zlib1g-dev
            - libpython3-all-dev
            - graphviz-dev
            - git

before_install:
    - base_dir=$(pwd)
    # Build monosat
    - git clone https://github.com/sambayless/monosat.git 
    - cd monosat
    - cmake .
    - make
    - sudo make install
    - cd src/monosat/api/python
    - sudo python3 setup.py install -f
    - cd base_dir
    # Build z3
    - git clone https://github.com/Z3Prover/z3.git
    - cd z3
    - python scripts/mk_make.py --python
    - cd build
    - make
    - sudo make install
    - cd base_dir


scripts:
    - cd ./mothball/new/
    - ./demo.sh


