dist: trusty

language: python

python: 3.6

cache:
    pip: true
    apt: true
    directories:
    - ./smt_solvers

env:
    - SOLVER=Z3
    - SOLVER=CVC4
    - SOLVER=Boolector

addons:
    apt:
        sources:
           - ubuntu-toolchain-r-test
        packages:
            #            - libpython3-all-dev
            - libgmp3-dev
            - git
            - cmake
            - zlib1g
            - zlib1g-dev
            - git
            - gcc-4.9
            - g++-4.9
            - build-essential
            - swig2.0
            - libcln-dev

before_install:
    - export CXX="g++-4.9"
    - export CC="gcc-4.9"
    - export COREIRCONFIG="g++-4.9"
    - export COREIR_b=dev
    - export PYCORE_b=dev
    - export SWITCH_b=master

install:
    # install pip packages
    - pip install pytest
    # get solvers
    - . ./util/get_smt_solvers.sh
    # Clone repos
    - git clone -b $SWITCH_b -- https://github.com/makaimann/smt-switch.git
    - git clone -b $COREIR_b -- https://github.com/rdaly525/coreir.git
    - git clone -b $PYCORE_b -- https://github.com/leonardt/pycoreir.git
    # Setup smt-switch 
    - export PYTHONPATH=$PYTHONPATH:$PWD/smt-switch
    # Build coreir
    - cd $TRAVIS_BUILD_DIR
    - cd coreir;
    - make -j2 all
    - sudo make -j2 install
    # install pycoreir
    - cd $TRAVIS_BUILD_DIR
    - pip install -e pycoreir
    # install pnrdoctor
    - pip install -e package

script:
    - echo Running tests with $SOLVER
    - ./test/test.sh
