language: python

python: "3.6"

addons:
    apt:
        packages:
            - libgmp3-dev
            - git
            - cmake
            - zlib1g
            - zlib1g-dev
            - graphviz-dev
            - git

before_install:
    # Build monosat
    - git clone https://github.com/sambayless/monosat.git 
    - cd monosat
    - cmake .
    - make
    - sudo make install
    - cd src/monosat/api/python
    - sudo python3 setup.py install -f
    - cd ../../../../../
    # Build z3
    - git clone https://github.com/Z3Prover/z3.git
    - cd z3
    - python scripts/mk_make.py --python
    - cd build
    - make
    - sudo make install
    - cd ../

scripts:
    - "./mothball/new/demo.sh"


