dist: trusty

language: python

python: 3.5

addons:
    apt:
        sources:
           - ubuntu-toolchain-r-test
        packages:
            #            - libpython3-all-dev
            - libgmp3-dev
            - git
            - cmake
            - zlib1g
            - zlib1g-dev
            - graphviz-dev
            - git
            - g++-4.9
            - build-essential

before_install:
    - export CXX="g++-4.9"
    - export CC="gcc-4.9"

install:
    # Build monosat
    - git clone https://github.com/sambayless/monosat.git 
    - cd monosat
    - cmake .
    - make -j 2
    - sudo make install
    - cd src/monosat/api/python
    - pip install -e .
    - cd $TRAVIS_BUILD_DIR
    # Build z3
    - wget https://github.com/Z3Prover/z3/releases/download/z3-4.5.0/z3-4.5.0-x64-ubuntu-14.04.zip
    - unzip z3-4.5.0-x64-ubuntu-14.04.zip
    - export PATH=$PATH:$PWD/z3-4.5.0-x64-ubuntu-14.04/bin/
    - export PYTHONPATH=$PYTHONPATH:$PWD/z3-4.5.0-x64-ubuntu-14.04/bin/python/
    - sudo ln -s $PWD/z3-4.5.0-x64-ubuntu-14.04/bin/libz3.so /usr/lib/libz3.so
    - cd $TRAVIS_BUILD_DIR
    # Build coreir
    - git clone https://github.com/rdaly525/coreir.git 
    - cd coreir
    - export CORECONFIG="g++-4.9";
    - make -C src
    - make -C src ../build/coreir.so  # For bindings tests
    - make -C tests
    - pip install pytest
    - pip install -e bindings/python
    - cd $TRAVIS_BUILD_DIR
    # Stuff needed for P&R
    - pip install pygraphviz
    - pip install lxml

script: 
    - cd ./src
    - ./test.py ../mapped.json ../cgra4x4.xml ../placed.xml ../io.xml



