dist: trusty

language: c

addons:
    apt:
        sources:
           - ubuntu-toolchain-r-test
        packages:
            - libpython3-all-dev
            - libgmp3-dev
            - git
            - cmake
            - zlib1g
            - zlib1g-dev
            - graphviz-dev
            - git
            - g++-4.9
            - build-essential

before_install:
    - export CXX="g++-4.9"
    - export CC="gcc-4.9"

install:
    # Build monosat
    - git clone https://github.com/sambayless/monosat.git 
    - cd monosat
    - cmake .
    - make
    - sudo make install
    - cd src/monosat/api/python
    - sudo python3 setup.py install -f
    - cd ../../../../../
    # Build z3
    - git clone https://github.com/Z3Prover/z3.git
    - cd z3
    - python scripts/mk_make.py --python
    - cd build
    - make
    - sudo make install
    - cd ../../

script: 
    - cd ./mothball/new/
    - ./demo.sh


