dist: trusty

language: python

python: 3.5

cache:
    apt: true
    directories:
    - ./smt_solvers

addons:
    apt:
        sources:
           - ubuntu-toolchain-r-test
        packages:
            #            - libpython3-all-dev
            - libgmp3-dev
            - git
            - cmake
            - zlib1g
            - zlib1g-dev
            - git
            - g++-4.9
            - build-essential
            - swig2.0
            - libcln-dev

before_install:
    - export CXX="g++-4.9"
    - export CC="gcc-4.9"

install:
    - . ./util/get_smt_solvers.sh
    # Add smt-switch
    - git clone https://github.com/makaimann/smt-switch.git
    - export PYTHONPATH=$PYTHONPATH:$PWD/smt-switch
    # Build z3
    #- wget https://github.com/Z3Prover/z3/releases/download/z3-4.5.0/z3-4.5.0-x64-ubuntu-14.04.zip
    #- unzip z3-4.5.0-x64-ubuntu-14.04.zip
    #- export PATH=$PATH:$PWD/z3-4.5.0-x64-ubuntu-14.04/bin/
    #- export PYTHONPATH=$PYTHONPATH:$PWD/z3-4.5.0-x64-ubuntu-14.04/bin/python/
    #- sudo ln -s $PWD/z3-4.5.0-x64-ubuntu-14.04/bin/libz3.so /usr/lib/libz3.so
    - cd $TRAVIS_BUILD_DIR
    # Build coreir
    - git clone -b master -- https://github.com/rdaly525/coreir.git
    - cd coreir;
    - export COREIRCONFIG="g++-4.9";
    - export COREIRHOME=$PWD
    - export COREIR=$PWD
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/bin:$PWD/lib
    - make -j 2 install py
    #- make -C src
    #- make -C src ../build/coreir.so  # For bindings tests
    #- make -C tests
    - cd $TRAVIS_BUILD_DIR
    # Stuff needed for P&R
    - pip install lxml

script:
    - cd ./src
    - ./test.py ../new_coremapped.json ../cgra4x4.xml
      --annotate ../bitstream
      --print --coreir-libs stdlib cgralib
    - cat ../bitstream
