echo "Adding paths to solvers"

: "${SMT_SOLVER_PATH:=$PWD/smt_solvers}"

echo Using SMT_SOLVER_PATH=$SMT_SOLVER_PATH

export PYTHONPATH=$PYTHONPATH:$SMT_SOLVER_PATH/cvc4
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SMT_SOLVER_PATH/cvc4

export PATH=$PATH:$SMT_SOLVER_PATH/monosat
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SMT_SOLVER_PATH/monosat

export PATH=$PATH:$SMT_SOLVER_PATH/z3/bin/
export PYTHONPATH=$PYTHONPATH:$SMT_SOLVER_PATH/z3/bin/python/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SMT_SOLVER_PATH/z3/bin

export PYTHONPATH=$PYTHONPATH:$SMT_SOLVER_PATH/boolector
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SMT_SOLVER_PATH/boolector
